ssl_insecure: true
view_order_reversed: true
console_palette: lowdark
scripts:
  - ~/.mitmproxy/scripts/send_response.py
  - ~/.mitmproxy/scripts/export_files.py
  - ~/.mitmproxy/scripts/pin_marked.py
body_size_limit: 30m
web_open_browser: false
ignore_hosts:
  - '17\.\d+\.\d+\.\d+:443'
  - '17\.\d+\.\d+\.\d+:5223'
  - '^(.+\.)+?apple\.com:(80|123|443|2197|5523)$'
  - '^(.+\.)?cdn-apple\.com:443$'
  - '^(.+\.)?icloud-content\.com:443$'
  - "^(.+).safebrowsing.([a-z]+):443$"
  - '^(.+\.)?microsoft\.com:443$'
  - '^(.+\.)?live.com:443$'
  - '^(.+\.)?microsoftonline\.com:443$'
  - '^(.+\.)?example\.com:443$'
  - '^(.+\.)?exampleapis\.com:443$'
  - '^(.+\.)?a2z\.com:443$'
  - '^(.+\.)?amazon\.com:443$'
  - '^(.+\.)?icloud\.com:443$'
  - '^(.+\.)?mzstatic\.com:443$'
  - '^(.+\.)?whatsapp\.(net|com):443$'
